[package]
name = "axum-graphql-example"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { version = "5.0.5", features = ["dataloader"] }
async-graphql-axum = "5.0.5"
axum = "0.6.3"
dotenvy = "0.15.6"
env_logger = "0.10.0"
log = "0.4.17"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "migrate", "offline"] }
tokio = { version = "1.24.1", features = ["full"] }
