[package]
name = "axum-graphql-example"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { version = "5.0.6", features = ["dataloader"] }
async-graphql-axum = "5.0.6"
axum = "0.6.7"
derive_more = "0.99.17"
dotenvy = "0.15.6"
env_logger = "0.10.0"
log = "0.4.17"
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "migrate", "offline"] }
tokio = { version = "1.25.0", features = ["full"] }
