[package]
name = "axum-graphql-example"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "postgres", "migrate", "offline"] }
tokio = { version = "1.23.0", features = ["full"] }
