[package]
name = "axum-graphql-example"
version = "0.1.0"
edition = "2021"

default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "sdl-export"
path = "src/sdl_export.rs"

[dependencies]
async-graphql = { version = "6.0.7", features = ["dataloader"] }
async-graphql-axum = "6.0.7"
axum = "0.6.20"
derive_more = "0.99.17"
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.20"
sqlx = { version = "0.7.1", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "migrate",
] }
tokio = { version = "1.32.0", features = ["full"] }
