[package]
name = "axum-graphql-example"
version = "0.1.0"
edition = "2021"

default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "sdl-export"
path = "src/sdl_export.rs"

[dependencies]
async-graphql = { version = "7.0.1", features = ["dataloader"] }
async-graphql-axum = "7.0.1"
axum = "0.7.4"
derive_more = "0.99.17"
dotenvy = "0.15.7"
env_logger = "0.11.1"
log = "0.4.20"
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "migrate",
] }
tokio = { version = "1.35.1", features = ["full"] }
