[package]
name = "axum-graphql-example"
version = "0.1.0"
edition = "2021"

default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "sdl-export"
path = "src/sdl_export.rs"

[dependencies]
async-graphql = { version = "5.0.8", features = ["dataloader"] }
async-graphql-axum = "5.0.8"
axum = "0.6.18"
derive_more = "0.99.17"
dotenvy = "0.15.7"
env_logger = "0.10.0"
log = "0.4.17"
sqlx = { version = "0.6.3", features = ["runtime-tokio-native-tls", "postgres", "migrate", "offline"] }
tokio = { version = "1.28.1", features = ["full"] }
