name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: CI=true cargo build
    - name: Run unit tests
      run: CI=true cargo test
