name: Rust

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: cargo fmt
        uses: actions-rust-lang/rustfmt@v1
      - run: cargo build
      - run: cargo clippy -- -D warnings
      - run: cargo test
